### ISSUE TITLE
V3.0b17 - Mail crashing on 10.11.6

### ISSUE THREAD

**Issue by gniemetz** [UniversalMailer/UniversalMailer#103]
Mail is constantly crashing on OS X 10.11.6 when sending a mail and UniversalMailer V3.0b16 is activated, see crashlog

Re-installed it, but no success

[universal_mailer_crash.txt](https://github.com/UniversalMailer/UniversalMailer/files/972604/universal_mailer_crash.txt)

**Comment by gniemetz** [comment]
Thanks for the new build, but unfortunately UniversalMailer V3.0b17 is crashing again on OS X 10.11.6

[universal_mailer_crash.txt](https://github.com/UniversalMailer/UniversalMailer/files/976525/universal_mailer_crash.txt)

**Comment by UniversalMailer** [comment]
Sorry about this, I fixed it blindly since I don't have a 10.11 to test it. I managed to produce another build, which should solve this second crash, could you give it a try, please? I'm not expecting any other crashes of this kind but trying is the best option :)

**Comment by gniemetz** [comment]
Thanks again, this time no crashes, looks promising

**Comment by UniversalMailer** [comment]
Ok then, I'll leave this thread open for a few days, feel free to close it if you're confident that the bug is solved.

Thanks!

**Comment by gniemetz** [comment]
So far so good, everything works properly, thanks
