### ISSUE TITLE
Need update for macOS High Sierra

### ISSUE THREAD

**Issue by macinapp** [UniversalMailer/UniversalMailer#107]
Error: "Incompatible Plug-In"

Please update the plugin for macOS 10.13 High Sierra. 

Thank you!

**Comment by UniversalMailer** [comment]
Updated to support macOS High Sierra. Beware that the plugin has not been modified, I've only updated the installation scripts to let it install and load on High Sierra. This means that you might encounter bugs or inconsistencies on the new OS (hopefully, everything will still be fine)
