### ISSUE TITLE
Universal Mailer Catalina support

### ISSUE THREAD

**Issue by alper020** [UniversalMailer/UniversalMailer#122]
I’m still waiting for the Catalina update.
When will it be available?

**Comment by P4TR1CKB** [comment]
Hey alper020.. 

There is a workaround for Catalina discussed in detail in issue #120 

You can add the following to the info.plist file in Library > Mail > Bundles for Universal Mailer

```
<key>Supported10.15PluginCompatibilityUUIDs</key>
<array>
<string># UUIDs for versions from 10.12 to 99.99.99</string>
<string># For mail version 12.0 (3445.100.39) on OS X Version 10.14.1 (build 18B45d)</string>
<string>A4343FAF-AE18-40D0-8A16-DFAE481AF9C1</string>
<string># For mail version 13.0 (3594.4.2) on OS X Version 10.15 (build 19A558d)</string>
<string>6EEA38FB-1A0B-469B-BB35-4C2E0EEA9053</string>
</array>
```

That should fix it ;) 

Happy Holidays..

**Comment by alper020** [comment]
Hello @P4TR1CKB,

Mine still doesn't work... :-(
This is what I have:

Mine still doesn't work... :-( This is what I have:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>16F73</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>UniversalMailer</string>
	<key>CFBundleIdentifier</key>
	<string>it.noware.UniversalMailer</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>UniversalMailer</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>3.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleVersion</key>
	<string>19</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>8E3004b</string>
	<key>DTPlatformVersion</key>
	<string>GM</string>
	<key>DTSDKBuild</key>
	<string>16E185</string>
	<key>DTSDKName</key>
	<string>macosx10.12</string>
	<key>DTXcode</key>
	<string>0833</string>
	<key>DTXcodeBuild</key>
	<string>8E3004b</string>
	<key>LastUsedVersionDirectoryName</key>
	<string>V7</string>
	<key>NSHumanReadableCopyright</key>
	<string>Copyright © 2017 noware. All rights reserved.</string>
	<key>NSPrincipalClass</key>
	<string>UniversalMailer</string>
	<key>SUFeedURL</key>
	<string>https://universalmailer.github.io/UniversalMailer/appcast/appcast.xml</string>
	<key>SUPublicDSAKeyFile</key>
	<string>dsa_pub.pem</string>
	<key>Supported10.15PluginCompatibilityUUIDs</key>
	<array>
		<string># UUIDs for versions from 10.12 to 99.99.99</string>
		<string># For mail version 12.0 (3445.100.39) on OS X Version 10.14.1 (build 18B45d)</string>
		<string>A4343FAF-AE18-40D0-8A16-DFAE481AF9C1</string>
		<string># For mail version 13.0 (3594.4.2) on OS X Version 10.15 (build 19A558d)</string>
		<string>6EEA38FB-1A0B-469B-BB35-4C2E0EEA9053</string>
	</array>
	<key>VersionDirectoryIdentifiers</key>
	<dict>
		<key>V7</key>
		<string>B74C5144-0547-465C-BF17-ABBF0B5909B1</string>
	</dict>
</dict>
</plist>

**Comment by P4TR1CKB** [comment]
Your whole .plist File should look something like this: 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>16F73</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>UniversalMailer</string>
	<key>CFBundleIdentifier</key>
	<string>it.noware.UniversalMailer</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>UniversalMailer</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>3.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleVersion</key>
	<string>19</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>8E3004b</string>
	<key>DTPlatformVersion</key>
	<string>GM</string>
	<key>DTSDKBuild</key>
	<string>16E185</string>
	<key>DTSDKName</key>
	<string>macosx10.12</string>
	<key>DTXcode</key>
	<string>0833</string>
	<key>DTXcodeBuild</key>
	<string>8E3004b</string>
	<key>NSHumanReadableCopyright</key>
	<string>Copyright © 2017 noware. All rights reserved.</string>
	<key>NSPrincipalClass</key>
	<string>UniversalMailer</string>
	<key>SUFeedURL</key>
	<string>https://universalmailer.github.io/UniversalMailer/appcast/appcast.xml</string>
	<key>SUPublicDSAKeyFile</key>
	<string>dsa_pub.pem</string>
	<key>Supported10.15PluginCompatibilityUUIDs</key>
	<array>
		<string># UUIDs for versions from 10.12 to 99.99.99</string>
		<string># For mail version 12.0 (3445.100.39) on OS X Version 10.14.1 (build 18B45d)</string>
		<string>A4343FAF-AE18-40D0-8A16-DFAE481AF9C1</string>
		<string># For mail version 13.0 (3594.4.2) on OS X Version 10.15 (build 19A558d)</string>
		<string>6EEA38FB-1A0B-469B-BB35-4C2E0EEA9053</string>
	</array>
</dict>
</plist>
```

Perhaps you could take a security copy of your existing file and just paste the whole thing?

**Comment by alper020** [comment]
This is what I did:

- closed the Mail.app
- deleted the Universal Mailer plugin (bundle)
- downloaded the Universal Mailer plugin again
- installed the Universal Mailer plugin
- went to Finder and replaced the .plist file (changed the extension into .plist)
- opened the Mail app and activated the Universal Mailer plugin

It still doesn't work... :-(

**Comment by alper020** [comment]
Problem solved!
