### ISSUE TITLE
Universal Mailer plugin doesn't work after update

### ISSUE THREAD

**Issue by alper020** [UniversalMailer/UniversalMailer#125]
Mail version 13.4 (3608.80.23.2.2)
macOS Catalina version 10.15.5

Can someone please send me the instructions and the Info.plist file?
Thanks a lot!

**Comment by P4TR1CKB** [comment]
Hey.. the info.plist is the same as for 10.15.4 ... as far as I can say the plugIn is not working because of the SIP (probably filesystem only) in macOS 10.15.5 ... It works fine when you deactivate SIP for the file system. unfortunately that won't work for me, because I don't want to deactivate SIP permanently...

**Comment by alper020** [comment]
Hello Patrick,

Thanks for the quick reply.
There's no other way to activate the plugin?

Kind regards,

Alper

**Comment by P4TR1CKB** [comment]
I would appreciate any other idea too :P The only thing I could think of right now, is to check the original sourceCode to find the "bug".. But as I have zero experience in C AND in Mail PlugIns it could possibly take a while if I would do it... :D

**Comment by alper020** [comment]
Deactivate SIP didn’t work... :-(
![CBE8FDF6-9743-4C62-8BB4-6076A992F067](https://user-images.githubusercontent.com/59112488/84908030-39e2fb00-b0b4-11ea-9793-eb7f6d3d42e9.jpeg)

**Comment by P4TR1CKB** [comment]
But the PlugIn did work in macOS 10.15.4?

**Comment by alper020** [comment]
Yes, Universal Mailer worked until the macOS update.

**Comment by alper020** [comment]
Can you please send me the .plist file again, just for sure. I will try again.
So, first I have to replace the .plist file. Then I have to deactivate SIP and enable Universal Mailer in Mail again?

**Comment by alper020** [comment]
![6C2387EE-E894-4D0D-9BC7-19185DF2075C](https://user-images.githubusercontent.com/59112488/84911040-ea063300-b0b7-11ea-8d68-670682d7b251.jpeg)

Did you try this?

**Comment by alper020** [comment]
Steps C and D didn't work for me... :-( Does someone have THE solution to get Universal Mailer worked?

**Comment by aus-coder** [comment]
I've tried everything suggested here and in MailButler forums. I also downloaded the code and compiled myself using a local certificate. Even tried after copying the bundle to `~/Library/Mail/Bundles/` instead of where it installs (`/Library/Mail/Bundles`).

Tried after compiling it in 64-bit mode, with new compiler, and few other things but nothing has worked. Of course it works when you disable SIP but that is not an option for me.

Sending this just as an update. Guess some of us remaining users have to make a clone and start to make changes to this so that it works with new Mail versions.

**Comment by alper020** [comment]
Hello @aus-coder !

Can you please send me a copy of the Info.plist file? I will try with disabled SIP too.

**Comment by aus-coder** [comment]
Here it is. Note that I changed it to work only with 10.5.5.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>19F101</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>UniversalMailer</string>
	<key>CFBundleIdentifier</key>
	<string>it.noware.UniversalMailer</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>UniversalMailer</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>3.0</string>
	<key>CFBundleSignature</key>
	<string>19F96</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleVersion</key>
	<string>19</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>11E608c</string>
	<key>DTPlatformVersion</key>
	<string>GM</string>
	<key>DTSDKBuild</key>
	<string>19E258</string>
	<key>DTSDKName</key>
	<string>macosx10.15</string>
	<key>DTXcode</key>
	<string>1150</string>
	<key>DTXcodeBuild</key>
	<string>11E608c</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.15</string>
	<key>NSHumanReadableCopyright</key>
	<string>Copyright © 2017 noware. All rights reserved.</string>
	<key>NSPrincipalClass</key>
	<string>UniversalMailer</string>
	<key>SUFeedURL</key>
	<string>https://universalmailer.github.io/UniversalMailer/appcast/appcast.xml</string>
	<key>SUPublicDSAKeyFile</key>
	<string>dsa_pub.pem</string>
	<key>Supported10.15PluginCompatibilityUUIDs</key>
	<array>
		<string>6EEA38FB-1A0B-469B-BB35-4C2E0EEA9053</string>
	</array>
	<key>SupportedPluginCompatibilityUUIDs</key>
	<array>
		<string>6EEA38FB-1A0B-469B-BB35-4C2E0EEA9053</string>
	</array>
</dict>
</plist>
```

**Comment by alper020** [comment]
Thanks, this worked!

**Comment by RonaldRegister** [comment]
were you able to get this working WITH SIP enabled?

**Comment by alper020** [comment]
@RonaldRegister No, SIP was disabled when installed and activated the plugin.

**Comment by RonaldRegister** [comment]
but does the plugin still work if you re-enable SIP after installing and activating?

**Comment by alper020** [comment]
@RonaldRegister No, SIP must stay disabled, otherwise it won’t work.

**Comment by RonaldRegister** [comment]
ai, thats not great. not an option for me. Thanks!
