### ISSUE TITLE
Image Attachments Not Shown on iOS

### ISSUE THREAD

**Issue by qpanda** [UniversalMailer/UniversalMailer#40]
I have option "Force all files as non inline" selected. When I attach an image (PNG, JPG, ...) to an email the attachment is not working / not shown on iOS (7.x) devices (iPhone, iPad). A paperclip icon (indicating that an attachment is present) is shown for this email in the message list but when I open the email no image / no attachment is shown. The image attachment works fine with all desktop email clients I tried. When I attach PDFs they show correctly as attachments on iOS. The issue seems to be specific to images.

It would be great if this could be fixed. Other than that Universal Mailer works great and allows me to send properly formatted emails to Outlook users!

**Comment by UniversalMailer** [comment]
V3 is out, should solve the issue
