### ISSUE TITLE
Email with all content disappears after pushing send button

### ISSUE THREAD

**Issue by david-eiler** [UniversalMailer/UniversalMailer#43]
There is a specific e-mail which I can repeatable forward with UniversalMailer enabled which disappears without any trace in the Outbox or Sent Items, and which never arrives at the receiver. There is also no warning that the sending process had any problem.

Once I disable UniversalMailer I can forward and sent the same e-mail without any problems and it can be found in Sent Items and in the Receivers Inbox.

Please help to resolve this issue because it's troublesome when assuming an e-mail has been sent but actually it's lost with all the content. At least a warning when sending was not possible would be helpful... 

Mail: Version 7.3 (1878.6)
UniversalMailer: 2.1.3
OSX: 10.9.4

**Comment by renier** [comment]
@UniversalMailer I had disabled universalmailer and just turned it back on. Happened again shortly thereafter. Using the latest 2.1.5.

3/8/15 3:04:47.401 PM Mail[226]: Universal Mailer encoutered a serious error while parsing the following email. Please file an issue with this log if possible. /Users/ibm/Library/Containers/com.apple.mail/Data/Library/Application Support/Mail/umailer-1190820.dat

At least I know where to rescue the email from. Then disable universalmailer, and re-send it.

**Comment by UniversalMailer** [comment]
Coming back to this, if you can send me the file pointed by the first line of log (/Users/me/Library/Containers/com.apple.mail/Data/Library/Application Support/Mail/umailer-1190820.dat).

It contains the entire email (headers, body and signature) that caused the issue and it might help solving it. Beware by 'entire email' I mean that I'll be able to read that specific email if you send me the file, be sure that no sensitive information are included in it.

**Comment by renier** [comment]
I can do that. Where do I send it?

**Comment by UniversalMailer** [comment]
You can send it to universal.mailer.noware at gmail.com, thanks!

**Comment by UniversalMailer** [comment]
V3 is out, should solve the issue
