### ISSUE TITLE
Wrong KOI8-r charset value in encodings.plist file

### ISSUE THREAD

**Issue by Tricheur-one** [UniversalMailer/UniversalMailer#49]
Hello!

Please correct encodings.plist file content:
KOI8-r charset key has value <integer>2147484165</integer>. This is the same value as for ISO-8859-5 charset. For KOI8-r the value should be <integer>2147486210</integer> (0x80000A02 HEX).

Users can get some sent message bodies unreadable in case the Mail App decides to use KOI8-r charset for the message body and the message has attachments.

Universal Mailer v2.1.5
OS X 10.10.x, Mail App v8.x

**Comment by UniversalMailer** [comment]
Thanks, fixed with commit 74287154841b3713df6df1c8124fa002d4e3bc96!
