### ISSUE TITLE
Disabled by Mail 8.1

### ISSUE THREAD

**Issue by johanventer** [UniversalMailer/UniversalMailer#50]
Hi,

I installed the latest Yosemite updates yesterday and Mail 8.1 now refuses to enable Universal Mailer - is there a way around this?

Johan

**Comment by bikubay** [comment]
same here

**Comment by snoblenet** [comment]
I had the same problem when Mail auto-updated to v8.2. I solved it by downloading and installing UniversalMailer again.

**Comment by johanventer** [comment]
Huh me too. Guess when I tried that the first time I must've done something wrong. Shutdown mail, reinstall Universal Mailer. Works.

**Comment by moloko** [comment]
reinstalling works for me too, thanks for the tip everyone

**Comment by marcelosomers** [comment]
I've quit mail, cleared out `~/Library/Mail/Bundles` and `/Library/Mail/Bundles`, and reinstalled and it's still disabled.
