### ISSUE TITLE
Does not work with Mail 10.11 El Capitan

### ISSUE THREAD

**Issue by simondsmason** [UniversalMailer/UniversalMailer#54]
Incompatible plugin

**Comment by tschortsch22** [comment]
Would love to see an updated version for OS X 10.11! :)

**Comment by simondsmason** [comment]
I downloaded and reinstalled the current build in El. Capitan and this removed the incompatible plugin message.  It appears in preferences, I haven't tested fully to see if it is working - but it does look like it is.
