### ISSUE TITLE
Mail 9.0 plz

### ISSUE THREAD

**Issue by goferit** [UniversalMailer/UniversalMailer#55]

**Comment by Neejoh** [comment]
Same problem here.
![screen shot 2015-10-15 at 09 21 00](https://cloud.githubusercontent.com/assets/7911547/10507072/323179b4-731e-11e5-8c55-f05be183cfc0.png)

**Comment by roman-1983** [comment]
https://github.com/UniversalMailer/UniversalMailer/pull/44

**Comment by Neejoh** [comment]
I got it working going through the steps under "After I launch Mail.app an alert complains about the plugin not being compatible" on the [FAQ](http://universalmailer.github.io/UniversalMailer/faq.html) page. I got a different SupportedPluginCompatibilityUUIDs than @roman-1983 posted though (just one, on El Capitan 10.11).

```
cat /Applications/Mail.app/Contents/Info.plist | grep UUID -A 1
```
gave me the string 
```
	<key>PluginCompatibilityUUID</key>
	<string>AB695A2B-4605-4A74-A99F-AF9F9C92C41B</string>
```

I added that to `/Library/Mail/Bundles/UniversalMailer.mailbundle/Contents/Info.plist` and the plugin now works again.

PS The faq says `~/Library/[..]` but that should be `/Library/[..]`

**Comment by jolyonhs** [comment]
That worked for me as well. I needed to 

`/Library/Mail/Bundles/UniversalMailer.mailbundle/Contents
MacBookAir:Contents jolyon$ sudo nano -w Info.plist`

**Comment by JayBrown** [comment]
You can also use the helper app MailPluginFix.

**Comment by UniversalMailer** [comment]
Another option is to run the installer of the latest version from the website: this will install and activate the plugin again.
