### ISSUE TITLE
mail 9.2: not compatible 

### ISSUE THREAD

**Issue by mhaghdoost** [UniversalMailer/UniversalMailer#56]
after upgrading mail a message appears after starting mail saying the plugin is note compatible :(

**Comment by Jen6566** [comment]
I'm having the same problem.  Apple Mail 9.2 won't let the plugin run.  Is there a plan to fix this?

**Comment by crozynski** [comment]
When you upgrade Mail you need to reinstall the plugin. See the 6th FAQ: http://universalmailer.github.io/UniversalMailer/faq.html
