### ISSUE TITLE
Mail 9.3 Please!!!

### ISSUE THREAD

**Issue by gregwilkinson** [UniversalMailer/UniversalMailer#59]
Dang! Forgot about this plugin before installing the latest Apple update.

**Comment by designhunger** [comment]
Simply download the plugin again and install it on your Mac. Just did the same and it worked out perfectly.

**Comment by gregwilkinson** [comment]
Thanks!! That worked, but I had to first uninstall (delete UniversalMailer.mailbundle from ~/Library/Mail/Bundles) then re-install the latest plugin.
