### ISSUE TITLE
Inline Images

### ISSUE THREAD

**Issue by emojidatabase** [UniversalMailer/UniversalMailer#63]
Images are always inline no matter what if "Allow inline images" is checked or not.

The Mail-Options "Always send Attachments Windows compatible" and "Insert Attachments always at the end of email" do not influence that.

**Comment by UniversalMailer** [comment]
Please send me a couple of emails at universal.mailer.noware at gmail.com, one with the inline option enabled and another without (of course with an image included). As per issue #64 it might be that the plugin is not loaded at all.

Also, please specify which version of the plugin are you using.

**Comment by emojidatabase** [comment]
Found it!

**The plugin did not work because of the S/MIME digital signature was activated.** 

![bildschirmfoto 2016-06-06 um 09 50 23 kopie](https://cloud.githubusercontent.com/assets/11026719/15815409/334c4afa-2bcd-11e6-81d0-68f68d6c2fd6.jpg)

If I deactivate it by clicking in the new email window – everything seems to work out just fine – attachments and fonts.

Unfortunately that is **not an option** for me because the email encryption would not work anymore.
This was just the SMIME signature. I can't test what happens if the email is also encrypted. I guess it is the same and not another obstacle.

**Comment by UniversalMailer** [comment]
That's correct: a long time ago the developer of GPGTools made a patch for this to avoid having UniversalMailer kicking in when a secure email has been detected. As discussed with him, having both GPGTools (or any other S/MIME application) and UniversalMailer is not feasible, at least not with ease.

I'll mark this thread as closed.
