### ISSUE TITLE
Text garbled issue（Not English ）

### ISSUE THREAD

**Issue by xinism** [UniversalMailer/UniversalMailer#70]
After download Build 12,
Text(English) + IMG + Attachment -> Good
Text(Chinese) + IMG + Attachment -> Garbled

**Comment by xinism** [comment]
![image](https://cloud.githubusercontent.com/assets/4794102/16344817/3ac86d7e-3a71-11e6-9fcb-d205617005d4.png)

**Comment by xinism** [comment]
![image](https://cloud.githubusercontent.com/assets/4794102/16344851/6cbc5930-3a71-11e6-961f-b7db713a8f62.png)

**Comment by chenxi0324** [comment]
I have the same issue,how to fix it !!!

**Comment by UniversalMailer** [comment]
Are you still experiencing the issue with the latest version (v3b15)?

**Comment by chenxi0324** [comment]
Thx a lot ! The v3b15 have fix the issue!
