### ISSUE TITLE
Default font won't stay selected

### ISSUE THREAD

**Issue by boulderbranding** [UniversalMailer/UniversalMailer#71]
Hi, I've downloaded the newest updates and still have a problem with my selected font (Verdana 12) - every time I open a new email or reply to an email it changes to Arial 12 and I have to manually change the font every time. I've checked both UM preferences and Apple Mail preferences and they are both correctly set, and I have restarted several times. OS X 10.11.5/Mail 9.3.

**Comment by UniversalMailer** [comment]
Are you still experiencing this issue with the latest version (v3b14)?

**Comment by boulderbranding** [comment]
No, thank you.




Stacey Kramer




303 541 0711 (desk)
303 506 1011 (handbag)
303 379 7226 (efax)

www.brandplay.com







On Aug 8, 2016, at 1:18 PM, Universal Mailer <notifications@github.com> wrote:

Are you still experiencing this issue with the latest version (v3b14)?
