### ISSUE TITLE
More then one letterfont

### ISSUE THREAD

**Issue by Bikkelpunten** [UniversalMailer/UniversalMailer#74]
In my original email tag I used two letterfonts
I like it when that will be a new feature.

**Comment by UniversalMailer** [comment]
Hi, can you describe with more detail the feature you are willing to have? The plugin at the moment sets a base, or default, font that is to be considered as a fallback if no other fonts have been specified in your text. Is this what you mean?

**Comment by Bikkelpunten** [comment]
i mean that in my signature I want to use two fonts.
One for the email text. and one for my company name.
In the picture you can see what I mean. I use two fonts, Myanmar and Orbitron



Sportieve groet,


Jurriaan Vis

**Comment by UniversalMailer** [comment]
Unfortunately, that's not what the plugin does (or it's meant for): the plugin provides a default fallback font for your emails, meaning that if you don'y specify a font in your text (or signature), it will ensure that the received email has a decent presentation.

Aside from this, I think that you can easily solve your problem by having UniversalMailer forcing the font of your text and then create a custom signature with the other font (see [here](http://mydesignpad.com/create-a-html-email-signature-for-mac-os-x-mountain-lion-10-8/) for a step by step guide on how to do this)
