### ISSUE TITLE
Compatibility and update request for MacOS Sierra

### ISSUE THREAD

**Issue by atomicsprite** [UniversalMailer/UniversalMailer#78]
Hi,

It transpires UM v2.1.6 is not compatible with Apple Mail Version 10.0 (3226) (MacOS Sierra).
Is there any timeline for an update?

Many thanks.

**Comment by UniversalMailer** [comment]
If you are on El Capitan or Sierra you should use version 3: version 2 is not mantained anymore. The 2.1.6 version is there in case you need it for special reasons and will not be updated in the future.
