### ISSUE TITLE
Not working properly with 10.12 - Bug

### ISSUE THREAD

**Issue by mikedvzo** [UniversalMailer/UniversalMailer#79]
I have been using this product for many years and as of recent it seems to not be working with 10.12.  When it is installed my font is not maintained and all of my message are coming through with very large fonts.  After I remove it everything functions fine.  See screenshot with and without it installed. Having it installed yet it is disabled still causes the problem.  I am forced to totally remove the product. Look at the screen shot and my Signature is correct with the Verdana 13 but the body of the message is not.  
![screen shot 2016-09-25 at 11 09 31 pm](https://cloud.githubusercontent.com/assets/2942239/18821581/95eb7ba4-8375-11e6-89ed-c85e839031a3.png)

![screen shot 2016-09-25 at 11 12 29 pm](https://cloud.githubusercontent.com/assets/2942239/18821585/9c316924-8375-11e6-8918-19502b7221d1.png)

**Comment by mikedvzo** [comment]
This is a better feel of how off it is.
![screen shot 2016-09-25 at 11 25 27 pm](https://cloud.githubusercontent.com/assets/2942239/18821782/64332ad8-8377-11e6-8d3e-6776eaa796e0.png)
![screen shot 2016-09-25 at 11 24 38 pm](https://cloud.githubusercontent.com/assets/2942239/18821783/64357b08-8377-11e6-89c2-bea9e82e5302.png)

**Comment by mikedvzo** [comment]
I tried totally removing it again and reinstalling and then running all the default write commands and it seems to be working again.  Sorry to be a bother.

**Comment by kecinzer** [comment]
Hello. I can confirm bug with digital signatures (SMIME) also. May be will be better to create own issue :).

**Comment by mikedvzo** [comment]
Moving Digital Signature Issue to separate Issue.  Confirmed that Pixels instead of points fixes the issue although I have always used Points in the past.  As long as UM is installed it will break Digital Signatures in 10.12 even if it is not enabled.
