### ISSUE TITLE
Incompatible with Mac OS 10.12.1

### ISSUE THREAD

**Issue by curdaneta** [UniversalMailer/UniversalMailer#84]
The last Mail.app bulid 10.1 (3251) disables UniversalMailer

> Mail has disabled the following plug-ins:
> 
> 	UniversalMailer
> 
> Contact the makers of these plug-ins for versions that are compatible with Mail 10.1.

![screen shot 2016-10-25 at 12 29 28 pm](https://cloud.githubusercontent.com/assets/5185821/19694805/b53ec4ca-9aae-11e6-8689-5c69b632ae43.png)

**Comment by UniversalMailer** [comment]
Please run the installer of the latest version to enable the plugin again.
