### ISSUE TITLE
Outgoing font issue

### ISSUE THREAD

**Issue by antjnr** [UniversalMailer/UniversalMailer#88]
When I'm sending an email and cut and past text into my email, even though it appears to be formatted correctly it ends up sending it like this:

<img width="191" alt="screenshot 2016-11-29 10 32 10" src="https://cloud.githubusercontent.com/assets/11939718/20702150/4b28b7e4-b61f-11e6-8873-2f33e9fc89b4.png">

The line with the smaller font size is the pasted text.

The only way around this seems to be to highlight all text, and reformat it before hitting send. 

My settings are as follows:
Font: Verdana, Regular, 13
Universal Mailer Outgoing font preferences  - Default font: Verdana, 10.0

**Comment by UniversalMailer** [comment]
Any custom font you set (by copying/pasting, by manually setting it etc) it is _not_ modified by the plugin and will never be, otherwise you'll end up with an email composer that can send emails with only one font, color and size (the one you specified), which is not good nor wanted...

**Comment by antjnr** [comment]
Yes but in mail, when I copy and paste, it says it’s Verdana size 13.  I have paged through character by character and it says (in the Mail app) that it’s Verdana 13.  The whole email is Verdana 13 supposedly but when I send, that bit is not.

On 29 Nov. 2016, at 10:48 am, Universal Mailer <notifications@github.com> wrote:

Any custom font you set (by copying/pasting, by manually setting it etc) it is not modified by the plugin and will never be, otherwise you'll end up with an email composer that can send emails with only one font, color and size (the one you specified), which is not good nor wanted...
