### ISSUE TITLE
Sierra update 10.12.2 breaks plugin

### ISSUE THREAD

**Issue by antjnr** [UniversalMailer/UniversalMailer#90]

**Comment by atomicsprite** [comment]
Hi, Is there any update available on resolving this issue?
Thanks in advance.

**Comment by lordyama** [comment]
I did a manual reinstall. Version 3.0 build 15 seems to work well.

**Comment by atomicsprite** [comment]
@lordyama please kindly provide more detail, by manual install you mean you simply run the installer: UniversalMailer.pkg or something else? I'm working with 10x Clean installs (plugin never been installed previously) of version 3.0 (Build 15). ta.

**Comment by lordyama** [comment]
I removed the plug-in and reinstalled the UniversalMailer.pkg. Nothing special.

**Comment by rflx** [comment]
@lordyama how do you removed the plugin? I've tried with the Mail Plugin Manager but it won't remove it. Is there a possibility to remove it manually? Im using osSierrra. Thanks in advice!

**Comment by lordyama** [comment]
@rflx I used Mail Plugin Manager but I think you can also remove the plug-ins manually from ~/Library/Mail/Bundles. Make sure that Mail is not running when you do this.

**Comment by rflx** [comment]
Thank you!

**Comment by Neejoh** [comment]
Same problem on 10.12.3.
I had to remove it (from `/Library/Mail/Bundles`, _not_ `in ~/Library/` and reinstall it, then it was fine.

**Comment by UniversalMailer** [comment]
Every time Apple updates Mail.app you'll have to run the installer again. The plugin is still compatible with the latest version of macOS Sierra (10.12.4 as of today).
