### ISSUE TITLE
Sierra 10.12.4 not working

### ISSUE THREAD

**Issue by danwoodsy** [UniversalMailer/UniversalMailer#96]
Mail 10.3 not compatible. Tried removing, re-installing, chasing directories, etc.

UUID is listed in SupportedPluginCompatibilityUUIDs as well.

**Comment by et01267** [comment]
I got it to work on 1.12.4 (per the FAQ):

- downloaded the latest installer 3b15 
- quit Mail
- run installer (have to ctrl-click and say open-with Installer)
- start Mail

**Comment by danwoodsy** [comment]
@et01267 well it turns out that 

> run installer (have to ctrl-click and say open-with Installer)

is the most important part as running the installer normally did not work at all for me.

**Comment by UniversalMailer** [comment]
Every time Apple updates Mail.app you'll have to run the installer again. The plugin is still compatible with the latest version of macOS Sierra (10.12.4 as of today).
