### ISSUE TITLE
Is there more info about the problem of inline attachments in general?

### ISSUE THREAD

**Issue by jmuheim** [UniversalMailer/UniversalMailer#97]
Hello

I'm used to send attachments inline, as I find it very useful to paste them directly into their written context instead of having them all grouped together in one place.

My boss uses Outlook, and he has the problem of those `ATT00001.htm` things. So he told me to fix it, as he says it's a problem of OSX Mail.

I'm wondering now: where exactly does this problem come from? Does OSX Mail indeed violate some mail standards? Or is Outlook "wrong"? Thunderbird seems to be able to receive my mails without a problem, though it displays the attachments also grouped together (which seems negligible).

I'm experimenting with UniversalMailer now, but still: I'd like to know "who's wrong", but I don't find very specific information online about this specific problem, only proposed work-arounds and solutions.

**Comment by UniversalMailer** [comment]
Hi,
 as far as I know there are no clear information on why the problem of ATT00001.htm shows up in Outlook.

From a trial and error process all I can say is that Mail.app produces a valid MIME structure (see here: https://en.wikipedia.org/wiki/MIME) but for some reasons either Outlook/Exchange or an intermediate Exchange Server will not understand it the way it's meant to be. Also, particular configurations of EWS will manipulate your email every time you send one (as an example, some companies add a 'save the environment and don't print this email' footer) and during this process the email structure is completely rewritten (don't ask why)

**Comment by jmuheim** [comment]
Thank you. Can you explain a little further to me, what you mean with "particular configurations of EWS" (what is EWS, by the way)?

So do you think it's rather an Apple or a Microsoft Exchange problem?

**Comment by UniversalMailer** [comment]
EWS is the Exchange Web Service, here I used it to refer to a generic Exchange Server instance (I'm not into this kind of things, it's just the concept). A "particular" configuration means that if you own an EWS server you might have it configured to add footers to all outgoing emails or something else like running an antivirus software etc.

Anyway imho it's a problem on the MS side, which is not fully compliant to the MIME standard. I'm however biased toward Apple so feel free to think something else :)

**Comment by jmuheim** [comment]
Thanks for explaining this.
